# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "US/Mountain"
    ignore:
      # dependencies
      - dependency-name: "core-js"
      - dependency-name: "next"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "reflect-metadata"
      - dependency-name: "regenerator-runtime"
      - dependency-name: "rxjs"
      - dependency-name: "tslib"
      # devDependencies
      - dependency-name: "@nrwl/cli"
      - dependency-name: "@nrwl/cypress"
      - dependency-name: "@nrwl/eslint-plugin-nx"
      - dependency-name: "@nrwl/jest"
      - dependency-name: "@nrwl/linter"
      - dependency-name: "@nrwl/nest"
      - dependency-name: "@nrwl/next"
      - dependency-name: "@nrwl/node"
      - dependency-name: "@nrwl/nx-cloud"
      - dependency-name: "@nrwl/react"
      - dependency-name: "@nrwl/web"
      - dependency-name: "@nrwl/workspace"
      - dependency-name: "@testing-library/react"
      - dependency-name: "@types/jest"
      - dependency-name: "@types/node"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
      - dependency-name: "@typescript-eslint/eslint-plugin"
      - dependency-name: "@typescript-eslint/parser"
      - dependency-name: "babel-jest"
      - dependency-name: "cypress"
      - dependency-name: "eslint"
      - dependency-name: "eslint-config-next"
      - dependency-name: "eslint-config-prettier"
      - dependency-name: "eslint-plugin-cypress"
      - dependency-name: "eslint-plugin-import"
      - dependency-name: "eslint-plugin-jsx-a11y"
      - dependency-name: "eslint-plugin-react"
      - dependency-name: "eslint-plugin-react-hooks"
      - dependency-name: "jest"
      - dependency-name: "jest-environment-jsdom"
      - dependency-name: "nx"
      - dependency-name: "prettier"
      - dependency-name: "react-test-renderer"
      - dependency-name: "sass"
      - dependency-name: "ts-jest"
      - dependency-name: "ts-node"
      - dependency-name: "typescript"


  - package-ecosystem: "docker"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "US/Mountain"

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "US/Mountain"
